=== unaibabe/Clases_web/EntornoServidor/XML/receta.dtd
<!ELEMENT Receta (Nombre,Descripcion?,Ingredientes?,Instrucciones?)>
    <!ELEMENT Nombre (#PCDATA)>
    <!ELEMENT Descripcion (#PCDATA)>
    <!ELEMENT Ingredientes (Ingrediente+)>
    <!ELEMENT Ingrediente (Cantidad,Item)>
    <!ELEMENT Cantidad (#PCDATA)>
    <!ATTLIST Cantidad unidad CDATA #REQUIRED>
    <!ELEMENT Item (#PCDATA)>
    <!ELEMENT Instrucciones (Paso+)>
    <!ELEMENT Paso (#PCDATA)>

=== unaibabe/Clases_web/EntornoServidor/XML/receta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Receta SYSTEM "receta.dtd">
<Receta>
    <Nombre>Tortilla de patatas</Nombre>
    <Descripcion>
        La tortilla de patatas tradicional y típica, tal y como la hacen todas las madres.
    </Descripcion>
    <Ingredientes>
        <Ingrediente>
            <Cantidad unidad="pieza">3</Cantidad>
            <Item>Patatas</Item>
        </Ingrediente>
        <Ingrediente>
            <Cantidad unidad="pieza">2</Cantidad>
            <Item>Huevos</Item>
        </Ingrediente>
        <Ingrediente>
            <Cantidad unidad="litro">0.1</Cantidad>
            <Item>Aceite</Item>
        </Ingrediente>
    </Ingredientes>
    <Instrucciones>
        <Paso>
            Pelar y cortar la patata en rodajas
        </Paso>
        <Paso>
            Poner aceite en una sartén
        </Paso>
    </Instrucciones>
</Receta>
