=== unaibabe/Clases_web/JavaScript/Intro_EntornoServidor/02_php_dtd/datos.dtd
<!ELEMENT datos (persona+)>
<!ELEMENT persona (nombre, edad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>

<!ATTLIST persona codigo ID #REQUIRED>

=== unaibabe/Clases_web/JavaScript/Intro_EntornoServidor/02_php_dtd/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- dtd document type definition -->
<!-- conjunto de reglas que definen la estructura del fichero xml (elementos y atributos) -->
<!DOCTYPE datos SYSTEM "datos.dtd" >
<datos>
    <persona codigo="a01">
        <nombre> Eva</nombre>
        <edad>34</edad>
    </persona>
    <persona codigo="a02">
        <nombre> Toni</nombre>
        <edad>25</edad>
    </persona>
    <persona codigo="a03">
        <nombre> Ger</nombre>
        <edad>27</edad>
    </persona>
    <persona codigo="a04">
        <nombre> Laura</nombre>
        <edad>45</edad>
    </persona>
</datos>
